name: Run Test

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Ajusta la versión de Node.js según tus necesidades

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test
