name: Run Test

on:
  push:
    branches:
    -main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/setup-node@v2
      with:
        node-version: 18.2

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test